name: "Salesforce Pipeline"
run-name: "Salesforce Pipeline Run"

on:
  push:

jobs:
  setup-salesforce:
    name: "Setup salesforce"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout code"
        uses: actions/checkout@v7.0.0

      - name: "Install Salesforce CLI"
        run: npm install --global @salesforce/cli@latest

      - name: "Check CLI version"
        run: sf --version

      - name: "Install Salesforce Code Analyser"
        run: |
          sf --help
          sf plugins install code-analyzer
        
      - name: "Authenticate with Salesforce"
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_EXACTPATH }}
        run: |
          echo "$SFDX_AUTH_URL"
          echo "$SFDX_AUTH_URL" > ./sfdxAuthUrl.txt
          sf org login sfdx-url --sfdx-url-file ./sfdxAuthUrl.txt --alias ExactPath --set-default
          rm ./sfdxAuthUrl.txt
        
