name: Test Pipeline
run-name: "Test Pipeline is running"

on:
  push:

jobs:
  build-and-validate:
    name: Build & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "This is a pipeline"

      - name: Ingo
        run: |
          - echo "This is line 1"
          - echo "This is line 2"
          - echo "This is line 3"
